# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package publish and Docker image publish

on:
  push:
    branches:
      - main

jobs:
  maven-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: 'maven'
        
    - name: Check Java version
      run: java -version

    - name: Verify with Maven
      run: mvn -B verify --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload artifact
      use: actions/upload-artifact@v3
      with: java-app
      path: '${{github.workspace}}/target/*.jar'

  docker-job:
    runs-on: ubuntu-latest
    needs: maven-job
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: java-app


      - name: Logging into Docker
        run: docker login ghcr.io -u kenyeresgeza -p ${{ github.token }}

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ghcr.io/kenyeresgeza/cubix/cloudnative/demo:actions

      - name: Publish Docker image
        run: docker push ghcr.io/kenyeresgeza/cubix/cloudnative/demo:actions